AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-api

  Sample SAM Template for serverless-api
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  EdTrackerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  EdTrackerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: server/lambda.handler
      Runtime: nodejs18.x
      CodeUri: .
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          NODE_ENV: production
          # Add your DB connection env vars here

  Uncomment and configure if you want to provision an RDS instance for PostgreSQL
  EdTrackerDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: ethanowens
      MasterUserPassword: password12345
      AllocatedStorage: 20

